name: Push to SEO

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' 

jobs:
  push_to_seo:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: blog_dev
          environment-file: ./etc/environment.yml
      - name: push to baidu
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ secrets.SITEMAP_URL }} -Outfile ./sitemap.txt
          python python/push_baidu_seo.py -./sitemap.txt ${{ secrets.BAIDU_SEO_TOKEN }}