name: Push to SEO

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' 

jobs:
  push_to_seo:
    runs-on: ubuntu-latest
    environment:
      name: seo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12' 
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r etc/requirements.txt
      - name: push to baidu
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ secrets.SITEMAP_URL }} -Outfile ./sitemap.txt
          Invoke-WebRequest -Uri ${{ secrets.SITEMAP_DEAD_URL }} -Outfile ./sitemap.dead.txt
          python python/push_baidu_seo.py ./sitemap.txt ${{ secrets.BAIDU_SEO_TOKEN }}
      - name: push to bing Index Now
        shell: pwsh
        run: |
          python python/push_bing_index_now.py ./sitemap.txt ${{ secrets.INDEX_NOW_TOKEN }}
      - name: push to google
        shell: pwsh
        run: |
          ${{ secrets.GOOGLE_API_JSON }} > google_api_json.json
          # 注意 secrets.GOOGLE_API_JSON 中内容需要使用 @""@引起来 以便于正确以字符串写入文件 否则会被pwsh直接解析为命令
          python python/push_google_seo.py ./sitemap.txt ./sitemap.dead.txt ./google_api_json.json