name: Push to SEO

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' 

jobs:
  post_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: pwsh
        run: |
          Write-Host ${{ secrets.BAIDU_SEO_TOKEN }}
          Write-Host ${{ secrets.INDEX_NOW_TOKEN }}